// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Copyright (c) 2026 ADBC Drivers Contributors
//
// This file has been modified from its original version, which is
// under the Apache License:
//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include <stdlib.h>

#include "adbc.h"

struct AdbcError* MariaDBErrorFromArrayStream(struct ArrowArrayStream*, AdbcStatusCode*);
AdbcStatusCode MariaDBDatabaseGetOption(struct AdbcDatabase*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseGetOptionBytes(struct AdbcDatabase*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseGetOptionDouble(struct AdbcDatabase*, const char*, double*, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseGetOptionInt(struct AdbcDatabase*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode MariaDBDatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode MariaDBDatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode MariaDBDatabaseSetOption(struct AdbcDatabase* db, const char* key, const char* value, struct AdbcError* err);
AdbcStatusCode MariaDBDatabaseSetOptionBytes(struct AdbcDatabase*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseSetOptionDouble(struct AdbcDatabase*, const char*, double, struct AdbcError*);
AdbcStatusCode MariaDBDatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t, struct AdbcError*);

AdbcStatusCode MariaDBConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionCommit(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionGetInfo(struct AdbcConnection* cnxn, const uint32_t* codes, size_t len, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionGetObjects(struct AdbcConnection* cnxn, int depth, const char* catalog, const char* dbSchema, const char* tableName, const char** tableType, const char* columnName, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionGetOption(struct AdbcConnection*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetOptionBytes(struct AdbcConnection*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetOptionDouble(struct AdbcConnection*, const char*, double*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetOptionInt(struct AdbcConnection*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetStatistics(struct AdbcConnection*, const char*, const char*, const char*, char, struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetStatisticNames(struct AdbcConnection*, struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode MariaDBConnectionGetTableSchema(struct AdbcConnection* cnxn, const char* catalog, const char* dbSchema, const char* tableName, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionGetTableTypes(struct AdbcConnection* cnxn, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionInit(struct AdbcConnection* cnxn, struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionNew(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionReadPartition(struct AdbcConnection* cnxn, const uint8_t* serialized, size_t serializedLen, struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionRelease(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionRollback(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionSetOption(struct AdbcConnection* cnxn, const char* key, const char* val, struct AdbcError* err);
AdbcStatusCode MariaDBConnectionSetOptionBytes(struct AdbcConnection*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode MariaDBConnectionSetOptionDouble(struct AdbcConnection*, const char*, double, struct AdbcError*);
AdbcStatusCode MariaDBConnectionSetOptionInt(struct AdbcConnection*, const char*, int64_t, struct AdbcError*);

AdbcStatusCode MariaDBStatementBind(struct AdbcStatement* stmt, struct ArrowArray* values, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode MariaDBStatementBindStream(struct AdbcStatement* stmt, struct ArrowArrayStream* stream, struct AdbcError* err);
AdbcStatusCode MariaDBStatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode MariaDBStatementExecuteQuery(struct AdbcStatement* stmt, struct ArrowArrayStream* out, int64_t* affected, struct AdbcError* err);
AdbcStatusCode MariaDBStatementExecutePartitions(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode MariaDBStatementExecutePartitionsTrampoline(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode MariaDBStatementExecuteSchema(struct AdbcStatement*, struct ArrowSchema*, struct AdbcError*);
AdbcStatusCode MariaDBStatementGetOption(struct AdbcStatement*, const char*, char*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBStatementGetOptionBytes(struct AdbcStatement*, const char*, uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode MariaDBStatementGetOptionDouble(struct AdbcStatement*, const char*, double*, struct AdbcError*);
AdbcStatusCode MariaDBStatementGetOptionInt(struct AdbcStatement*, const char*, int64_t*, struct AdbcError*);
AdbcStatusCode MariaDBStatementGetParameterSchema(struct AdbcStatement* stmt, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode MariaDBStatementNew(struct AdbcConnection* cnxn, struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode MariaDBStatementPrepare(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode MariaDBStatementRelease(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode MariaDBStatementSetOption(struct AdbcStatement* stmt, const char* key, const char* value, struct AdbcError* err);
AdbcStatusCode MariaDBStatementSetOptionBytes(struct AdbcStatement*, const char*, const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode MariaDBStatementSetOptionDouble(struct AdbcStatement*, const char*, double, struct AdbcError*);
AdbcStatusCode MariaDBStatementSetOptionInt(struct AdbcStatement*, const char*, int64_t, struct AdbcError*);
AdbcStatusCode MariaDBStatementSetSqlQuery(struct AdbcStatement* stmt, const char* query, struct AdbcError* err);
AdbcStatusCode MariaDBStatementSetSubstraitPlan(struct AdbcStatement* stmt, const uint8_t* plan, size_t length, struct AdbcError* err);

AdbcStatusCode AdbcDriverMariaDBInit(int version, void* rawDriver, struct AdbcError* err);

static inline void MariaDBerrRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void MariaDB_release_error(struct AdbcError* error);

struct MariaDBError {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void MariaDBReleaseErrWithDetails(struct AdbcError* error);

int MariaDBErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail MariaDBErrorGetDetail(const struct AdbcError* error, int index);

int MariaDBArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream, struct ArrowSchema* out);
int MariaDBArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream, struct ArrowArray* out);
